import { store } from "@/store/store";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Provider } from "react-redux";
import { StoreProvider } from "@/store/StoreProvider";
import MainNavber from "@/components/shared/Navber/MainNavber";
import TextScrolling from "@/components/shared/InfiniteScrolling/TextScrolling";
import { Footer } from "@/components/shared/Footer/Footer";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <TextScrolling />
          <MainNavber />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
