import { Inter } from "next/font/google";
import "./globals.css";
import MainNavber from "./components/Shared/Navber/MainNavber";
import { StoreProvider } from "@/store/StoreProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainNavber />
          <ToastContainer />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
