"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sheard/Sidebar/Sidebar";
import { Provider } from "react-redux";
import { ClerkProvider } from "@clerk/nextjs";
import MainNavber from "./components/Sheard/Navber/MainNavber";
import { store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Provider store={store}>
          <body className={`${inter.className} flex`}>
            <Sidebar />
            <div className="w-full">
              <MainNavber />
              {children}
            </div>
          </body>
        </Provider>
      </html>
    </ClerkProvider>
  );
}
